### ISSUE TITLE
💡 Hinweis: There a some `404` requests - Can we change that?

### ISSUE THREAD

**Issue by deleonio** [public-ui/lab-micro-frontends#5]
Wenn wir `npm start` eingeben und die Seite im Browser angezeigt wird, gibt es ein paar 404 Requests. Ggf. können wir was beim ESM-Laden verbessern.

<img width="835" alt="image" src="https://github.com/public-ui/lab-micro-frontends/assets/6279703/ec800b64-29ec-4cc8-b62b-930de78ce1dd">

**Comment by sdvg** [comment]
Die Requests kommen von den Apps (React, Vue), die ohne Bundler direkt in die index.html eingebunden sind und Chunks nachladen wollen. Diese Apps wissen nicht (können nicht wissen), wo ihre Chunks/Assets zu finden sind. Anders verhält es sich hier bei Angular, wo direkt ESM-Imports verwendet werden, die auch mit relativen Pfaden umgehen können.

Beispiel-Request:

Ist: `/assets/tooltip-align-a16d498e.js`
Soll: `/node_modules/@public-ui/micro-frontend-vue/dist/assets/tooltip-align-a16d498e.js`

Einfache Lösung für jetzt: Wir deaktivieren das Aufteilen in mehrere Chunks.

Mögliche bessere Lösungen für die Zukunft:
a) Wir konfigurieren einen Bundler für die Beispiel-Anwendung (gerade nur statische index.html) 
b) Wir Konfigurieren die Vite/Rollups-Builds analog zu Angular, sodass nur ESM-Imports verwendet werden. (Hier habe ich keine schnelle Lösung gefunden, sollte aber mgl. sein.)

---

Nachdem der Fehler behoben ist, [werden neue Fehler sichtbar, die in neueren KoliBri-Versionen bereits behoben wurden](https://github.com/public-ui/kolibri/issues/6545#issuecomment-2185824849). Diese würde ich für den Moment ignorieren.

![screenshot 2024-10-15-11 48 59@2x](https://github.com/user-attachments/assets/886cd4bc-c404-47e6-88d7-f240f79c1fdf)
